version: '3.9'

services:
    core-db:
        image: postgres
        env_file: .env
        ports: 
            - "5440:5432"
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
            timeout: 3s
            interval: 5s
            retries: 3
        
    core:
        build: ./
        env_file: .env
        volumes:
            - ./:/var/www
        ports: 
            - "8000:8000"
        depends_on:
            core-db:
                condition: service_healthy
        command: sh -f entrypoint.sh